import { auth } from "@/auth";
import { db } from "@/lib/db";
import { competitorAnalyses, listingAnalyses, opportunities } from "@/lib/db/schema";
import { desc, eq } from "drizzle-orm";
import { ArrowRight, Radar, Search, Sparkles, Swords } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import type { ReactNode } from "react";

export default async function AnalysisPage() {
  const session = await auth();
  const userId = session?.user?.id;

  if (!userId) {
    redirect("/login");
  }

  const [listingItems, competitorItems, opportunityItems] = await Promise.all([
    db.query.listingAnalyses.findMany({
      limit: 4,
      orderBy: [desc(listingAnalyses.createdAt)],
      where: eq(listingAnalyses.userId, userId),
    }),
    db.query.competitorAnalyses.findMany({
      limit: 4,
      orderBy: [desc(competitorAnalyses.createdAt)],
      where: eq(competitorAnalyses.userId, userId),
    }),
    db.query.opportunities.findMany({
      limit: 4,
      orderBy: [desc(opportunities.createdAt)],
      where: eq(opportunities.userId, userId),
    }),
  ]);

  return (
    <div className="space-y-10">
      <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div className="space-y-3">
          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-500/20 bg-indigo-500/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.25em] text-indigo-300">
            <Sparkles className="h-3 w-3" />
            Intelligence Library
          </div>
          <h1 className="text-4xl font-black tracking-tight text-white">Your analysis surface</h1>
          <p className="max-w-3xl text-sm leading-relaxed text-gray-400">
            Review listing audits, competitor breakdowns, and niche opportunities generated by ORVEX.
            Each artifact is persisted separately from workflow runs so the system can scale cleanly as new workflow types are added.
          </p>
        </div>
        <Link href="/dashboard/workflows/new" className="inline-flex rounded-2xl bg-white px-5 py-3 text-sm font-bold text-black transition hover:bg-gray-200">
          Start new workflow
        </Link>
      </header>

      <div className="grid gap-8 xl:grid-cols-3">
        <AnalysisColumn
          title="Listing Intelligence"
          description="SEO and conversion scorecards from scraped listings."
          icon={<Search className="h-4 w-4" />}
          emptyCtaHref="/dashboard/workflows/new?mode=listing"
          emptyCtaLabel="Analyze a listing"
          items={listingItems.map((item) => ({
            href: `/dashboard/workflows/${item.workflowId}`,
            kicker: `Score ${item.listingScore}`,
            summary: item.sourceUrl,
            title: item.listingTitle,
          }))}
        />

        <AnalysisColumn
          title="Competitor Analyzer"
          description="Strategic breakdowns and differentiation angles."
          icon={<Swords className="h-4 w-4" />}
          emptyCtaHref="/dashboard/workflows/new?mode=competitor"
          emptyCtaLabel="Analyze a competitor"
          items={competitorItems.map((item) => ({
            href: `/dashboard/workflows/${item.workflowId}`,
            kicker: `v${item.analysisVersion} • ${item.keywordOpportunities.length} keyword gaps`,
            summary: item.sourceUrl || item.inputLabel,
            title: item.inputLabel,
          }))}
        />

        <AnalysisColumn
          title="Opportunity Engine"
          description="Demand, competition, and product-idea reports for new niches."
          icon={<Radar className="h-4 w-4" />}
          emptyCtaHref="/dashboard/workflows/new?mode=opportunity"
          emptyCtaLabel="Generate an opportunity report"
          items={opportunityItems.map((item) => ({
            href: `/dashboard/workflows/${item.workflowId}`,
            kicker: `Opportunity ${item.opportunityScore}`,
            summary: `${Array.isArray(item.productIdeas) ? item.productIdeas.length : 0} product ideas`,
            title: item.keyword,
          }))}
        />
      </div>
    </div>
  );
}

function AnalysisColumn({
  description,
  emptyCtaHref,
  emptyCtaLabel,
  icon,
  items,
  title,
}: {
  description: string;
  emptyCtaHref: string;
  emptyCtaLabel: string;
  icon: ReactNode;
  items: Array<{
    href: string;
    kicker: string;
    summary: string;
    title: string;
  }>;
  title: string;
}) {
  return (
    <section className="rounded-[2rem] border border-white/5 bg-[#141417] p-6">
      <div className="mb-6 flex items-center gap-3">
        <div className="rounded-2xl bg-indigo-500/10 p-3 text-indigo-300">{icon}</div>
        <div>
          <h2 className="text-xl font-black text-white">{title}</h2>
          <p className="text-sm text-gray-400">{description}</p>
        </div>
      </div>

      {items.length > 0 ? (
        <div className="space-y-3">
          {items.map((item) => (
            <Link
              key={item.href}
              href={item.href}
              className="block rounded-3xl border border-white/5 bg-[#0A0A0B] p-5 transition hover:border-white/10"
            >
              <p className="text-[11px] font-bold uppercase tracking-[0.2em] text-indigo-300">{item.kicker}</p>
              <h3 className="mt-2 line-clamp-2 text-lg font-bold text-white">{item.title}</h3>
              <p className="mt-2 line-clamp-2 text-sm text-gray-400">{item.summary}</p>
              <div className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-gray-500">
                Open result
                <ArrowRight className="h-3 w-3" />
              </div>
            </Link>
          ))}
        </div>
      ) : (
        <div className="rounded-3xl border border-dashed border-white/10 bg-[#0A0A0B] p-8 text-center">
          <p className="text-sm text-gray-400">No saved analysis artifacts yet.</p>
          <Link href={emptyCtaHref} className="mt-5 inline-flex rounded-2xl bg-white px-4 py-3 text-sm font-bold text-black">
            {emptyCtaLabel}
          </Link>
        </div>
      )}
    </section>
  );
}
